apiVersion: apps/v1
kind: Deployment
metadata:
  name: twito-celery
  labels:
    app: twito
spec:
  replicas: 1
  selector:
    matchLabels:
      app: twito
  template:
    metadata:
      labels:
        app: twito
    spec:
      containers:
      - name: twito-celery
        image: twito
        command:
          - celery
          - -A
          - tasks
          - worker
          - --loglevel=INFO
        env:
          - name: APP_ENV
            value: production
        envFrom:
          - secretRef:
              name: db-credentials
          - secretRef:
              name: redis-credentials
      - name: twito-celery-beat
        image: twito
        command:
          - celery
          - -A
          - tasks
          - beat
          - --loglevel=INFO
        env:
          - name: APP_ENV
            value: production
        envFrom:
          - secretRef:
              name: db-credentials
          - secretRef:
              name: redis-credentials
        resources:
          requests:
            memory: 1Gi
            cpu: 500m
          limits:
            memory: 1Gi
            cpu: 500m
