
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: twito
resources:
  - celery.yaml
  - twito.yaml
  - ingress.yaml
  - service.yaml
images:
- name: twito
  newName: rg.fr-par.scw.cloud/djnd/twito
  newTag: '5cb406583b122d4c2e673b5a5dad8c745a7bbcc7'
- name: twito-frontend
  newName: rg.fr-par.scw.cloud/djnd/twito-frontend
  newTag: '5cb406583b122d4c2e673b5a5dad8c745a7bbcc7'
