
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: twito
resources:
  - celery.yaml
  - twito.yaml
  - ingress.yaml
  - service.yaml
images:
- name: twito
  newName: rg.fr-par.scw.cloud/djnd/twito
  newTag: '1662b26d8ab56fddfe5395707a18dd7545e666f8'
- name: twito-frontend
  newName: rg.fr-par.scw.cloud/djnd/twito-frontend
  newTag: '1662b26d8ab56fddfe5395707a18dd7545e666f8'
