
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: twito-staging
resources:
  - celery.yaml
  - twito.yaml
  - ingress.yaml
  - service.yaml
images:
- name: twito
  newName: rg.fr-par.scw.cloud/djnd/twito
  newTag: 'cf1e8800daa609b93ff8d8c042e8dd38cea6722a'
- name: twito-frontend
  newName: rg.fr-par.scw.cloud/djnd/twito-frontend
  newTag: 'cf1e8800daa609b93ff8d8c042e8dd38cea6722a'
