
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: twito
resources:
  - celery.yaml
  - twito.yaml
  - ingress.yaml
  - service.yaml
images:
- name: twito
  newName: rg.fr-par.scw.cloud/djnd/twito
  newTag: '82b6732a1d8f2c4933cbc1e8bfea477725773beb'
- name: twito-frontend
  newName: rg.fr-par.scw.cloud/djnd/twito-frontend
  newTag: '82b6732a1d8f2c4933cbc1e8bfea477725773beb'
