
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: twito-staging
resources:
  - celery.yaml
  - twito.yaml
  - ingress.yaml
  - service.yaml
images:
- name: twito
  newName: rg.fr-par.scw.cloud/djnd/twito
  newTag: 'aba5e0b54ae8c9315bf596aa37c3c4cfc61c3a61'
- name: twito-frontend
  newName: rg.fr-par.scw.cloud/djnd/twito-frontend
  newTag: 'aba5e0b54ae8c9315bf596aa37c3c4cfc61c3a61'
