# Generated by Django 3.1.4 on 2021-01-01 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailySums',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('number_of_tweets', models.IntegerField(default=0)),
                ('seconds_online', models.IntegerField(default=0)),
                ('original_tweets', models.IntegerField(default=0)),
                ('retweets', models.IntegerField(default=0)),
                ('retweets_with_comment', models.IntegerField(default=0)),
            ],
        ),
    ]
