# Generated by Django 3.1.4 on 2021-01-17 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='user_id',
            new_name='user_handle',
        ),
    ]
