# Generated by Django 3.1.4 on 2021-01-17 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_auto_20210117_0814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='time',
            new_name='timestamp',
        ),
    ]
