# Generated by Django 3.2 on 2021-05-18 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0003_auto_20210117_0819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='truncated',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='user_name',
        ),
        migrations.AddField(
            model_name='tweet',
            name='quote',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tweet',
            name='quote_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='retweet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tweet',
            name='retweet_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='retweet_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='retweet_quote',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tweet',
            name='retweet_quote_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='retweet_timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
