# Generated by Django 3.2 on 2021-05-18 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0004_auto_20210518_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='retweet_id',
            field=models.TextField(null=True),
        ),
    ]
