"""tweet index

Revision ID: 51e818dff5de
Revises: 55281cba0c6c
Create Date: 2020-12-20 23:46:21.683249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51e818dff5de'
down_revision = '55281cba0c6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'tweets', ['twitter_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tweets', type_='unique')
    # ### end Alembic commands ###
