"""initial migration

Revision ID: 55281cba0c6c
Revises: 
Create Date: 2020-12-20 23:37:11.317298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55281cba0c6c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tweets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('twitter_id', sa.String(), nullable=False),
    sa.Column('favorite_count', sa.Integer(), nullable=True),
    sa.Column('filter_level', sa.String(), nullable=True),
    sa.Column('from_user_created_at', sa.DateTime(), nullable=True),
    sa.Column('from_user_description', sa.String(), nullable=True),
    sa.Column('from_user_favourites_count', sa.Integer(), nullable=True),
    sa.Column('from_user_followercount', sa.Integer(), nullable=True),
    sa.Column('from_user_friendcount', sa.Integer(), nullable=True),
    sa.Column('from_user_id', sa.String(), nullable=True),
    sa.Column('from_user_lang', sa.String(), nullable=True),
    sa.Column('from_user_listed', sa.String(), nullable=True),
    sa.Column('from_user_name', sa.String(), nullable=True),
    sa.Column('from_user_profile_image_url', sa.String(), nullable=True),
    sa.Column('from_user_timezone', sa.String(), nullable=True),
    sa.Column('from_user_tweetcount', sa.Integer(), nullable=True),
    sa.Column('from_user_url', sa.String(), nullable=True),
    sa.Column('from_user_utcoffset', sa.String(), nullable=True),
    sa.Column('from_user_verified', sa.Integer(), nullable=True),
    sa.Column('from_user_withheld_scope', sa.String(), nullable=True),
    sa.Column('from_user_realname', sa.String(), nullable=True),
    sa.Column('in_reply_to_status_id', sa.String(), nullable=True),
    sa.Column('lang', sa.String(), nullable=True),
    sa.Column('lat', sa.String(), nullable=True),
    sa.Column('lng', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('possibly_sensitive', sa.Integer(), nullable=True),
    sa.Column('quoted_status_id', sa.String(), nullable=True),
    sa.Column('retweet_count', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('time', sa.Integer(), nullable=True),
    sa.Column('to_user_name', sa.String(), nullable=True),
    sa.Column('truncated', sa.String(), nullable=True),
    sa.Column('withheld_copyright', sa.String(), nullable=True),
    sa.Column('withheld_scope', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('urls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('short_url', sa.String(), nullable=False),
    sa.Column('resolved_url', sa.String(), nullable=True),
    sa.Column('domain', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tweets_urls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tweet_id', sa.Integer(), nullable=False),
    sa.Column('url_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tweet_id'], ['tweets.id'], ),
    sa.ForeignKeyConstraint(['url_id'], ['urls.id'], ),
    sa.PrimaryKeyConstraint('id', 'tweet_id', 'url_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tweets_urls')
    op.drop_table('urls')
    op.drop_table('tweets')
    # ### end Alembic commands ###
